languageCode = "en"
languageName = "English"
weight = 2
title = "Xinyuan's home"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  logo = "img/IMG_202512162268_50x50 4.png"
  description = "My awesome website"
  copyright = "Global visitor map"
  dateFormat = "2 January 2026"

[params.author]
  name = "Associate Professor, Xinyuan Gao"
  image = "/img/avatar.png"
  headline = "Institute of Ocean Engineering, Northeastern University"
  bio = "The Institute of Ocean Engineering at Northeastern University was established on the occasion of the university's centennial celebration. Located at the Qinhuangdao, it aims to respond to the national strategy of building a maritime power and promote self-reliance in marine science and technology."
   links = [
     { google = "https://scholar.google.com/citations?user=Y_K9H_cAAAAJ&hl=zh-CN"},
     { github = "https://github.com/Gaoxy1118" },
     { orcid = "https://orcid.org/0009-0007-2831-3956" },
     { email = "mailto:gaoxy_cup@163.com" }
   ]
