languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
title = "高鑫远-主页"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  logo = "img/IMG_202512162268_50x50.png"
  description = "My awesome website"
  copyright = "Global visitor map"
  dateFormat = "2 January 2026"

[params.author]
  name = "高鑫远 副教授"
  image = "/img/avatar.png"
  headline = "东北大学 海洋工程研究院"
  bio = "东北大学海洋工程研究院成立于百年校庆之际，位于秦皇岛分校，旨在响应国家海洋强国战略，推动海洋科技自立自强。"
   links = [
     { google = "https://scholar.google.com/citations?user=Y_K9H_cAAAAJ&hl=zh-CN"},
     { github = "https://github.com/Gaoxy1118" },
     { orcid = "https://orcid.org/0009-0007-2831-3956" },
     { email = "mailto:gaoxy_cup@163.com" }
   ]
